services:
  - type: web           # <-- dynamic Node.js web service
    name: lookmeup-web  # any unique name
    env: node           # tells Render to spin up a Node runtime
    plan: free          # or “starter”, “professional”, etc.
    repo: https://github.com/your-username/LookMeUp
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run preview  # or “serve -s dist” if you install “serve”
    envVars:
      - key: VITE_GITHUB_TOKEN
        fromSecret: GITHUB_TOKEN
