# render.yaml (at the same level as package.json, src/, public/, etc.)
services:
  - type: static
    name: lookmeup-static
    env: static
    repo: https://github.com/Ajthompson88/LookMeUp  # ← your real GitHub URL
    branch: main
    buildCommand: npm install && npm run build
    publishDirectory: dist
    envVars:
      - key: VITE_GITHUB_TOKEN
        fromSecret: GITHUB_TOKEN
